### PR TITLE
Add support for other WebDriver implementations then RemoteWebDriver

### PR DESCRIPTION
**Pull request by nilols**
When running the same test on multiple platforms it's sometime necessary to access other functionality then the RemoteWebDriver implements. e.g. tap or swipe on a mobile phone. So instead of reimplement this functionality we can utilize this functionality from specific WebDriver implementations if GridWebDriver could have other implementations then RemoteWebDriver.

This PR change the GridWebDriver into a interface and add a GridWebDriverFactory that will return a specific WebDriver implementation based on the specified platformName capability.

If none or unknown platformName is defined a RemoteWebDriver will be created

Example of usage:

``` java
public void doSomething(GridWebDriver driver) {
  if (driver instanceof AppiumDriver) {
    // do this e.g. tap on screen
  } else {
    // do that e.g. click on element
  }
}
```

### CODE REVIEW

**Comment by mimfgg** [comment]
Hi Nils,

There is an rmtest-appium module ... that does basically that.
Have a look at
https://github.com/RedmindAB/RMTest/blob/develop/java/rmtest-appium/src/main/java/se/redmind/rmtest/config/AppiumConfiguration.java

Cheers,
Jeremy

**Comment by mimfgg** [comment]
oh, sorry, I read too fast. 

you added a dependency to appium in rmtest-selenium, which makes the rmtest-module kind of redundant, and pull appium in the selenium module ...

If I am correct, you can already achieve what you want with:
`driverWrapper.getCapability().getPlatform() == Platform.ANDROID`

see https://github.com/RedmindAB/RMTest/blob/develop/java/rmtest-example/src/main/java/se/redmind/rmtest/selenium/example/RMExample.java

**Comment by nilols** [comment]
hmm I see that now, I've missed the @FilterDrivers functionality. Yes the dependencies get a bit screwed up by this PR

thanks
/nils

**Comment by nilols** [comment]
I still have a problem with this =(

Our configuration is made in JSON and we execute tests on the grid, the grid have both desktop and mobile browsers, when running a test on a mobile browser we have the need to tap, which is available through the AppiumDriver but with our setup a GridConfiguration is created which can only create GridWebDriver (RemoteWebDriver) drivers.

**Comment by mimfgg** [comment]
Hmm, I see, maybe there would be a cleaner approach through the appium
module. If you want I can try something during the weekend...

Otherwise, you could add a protected createDriver method in the
GridConfiguration class and create a new AppiumGridConfiguration class in
the appium module extending the original one. Extend the create method to
return the appium drivers and set the json type annotation to appium-grid
or something similar. Add rmtest-appium as a dependency to your project and
fix your config file and you should be good to go. You will need to switch
to the yaml syntax though, to be able to set your driver type correctly.

You can probably revert the changes you made to rmtest-selenium.

I'm not in front of a computer right now, but it should be close to that ...

**Comment by SnytaxError** [comment]
Im working on this with Nils if you dont have any other suggestions @mimfgg?

**Comment by mimfgg** [comment]
Nop, I didn't really have time this weekend :) but it should pretty straight forward by adding a new type of configuration in the appium module.

**Pull request closed without merging**
