### PR TITLE
another take on the appium grid configuration

### PR DESCRIPTION
**Pull request by mimfgg**

### CODE REVIEW

**Comment by SnytaxError** [comment]
Looks good to me! I think we should merge this and make a release?

**Comment by mimfgg** [comment]
If you made sure that it works for you guys, go ahead :)

**Comment by SnytaxError** [comment]
I will give it a testrun before we merge, for some reason i have not received any notification for this PR.

**Comment by mimfgg** [comment]
Do that, I didn't have any appium setup to test it against ...

**Comment by petost** [comment]
The Jenkins server had a full disk, did come cleanup so this will build now.

**Comment by mimfgg** [comment]
Thanks!

**Comment by petost** [comment]
Status is that jenkins is up and sonar is up.
For some reason the is an authentication problem in sonar, so neither me or jenkins can log in.
Investigating

**Pull request merged**
