### PR TITLE
Deploy of version 2.8.2

### PR DESCRIPTION
**Pull request by mimfgg**
Hi guys, 

I have realised that the appium grid configuration patch never went live...
otherwise, it's mostly some code clean up and a fix in the google.feature example file.
I don't know if the jenkins machine is still setup to deploy automatically though...

Best, 
Jeremy

### CODE REVIEW

**Comment by petost** [comment]
Hi
Jenkins responds with a 500 at the moment.
http://redmind.se/jenkins
I expanded the volume for our EC2 instance last week, that might be related.
I am looking in to it.



[Redmind signatur]

PETTER ÖSTERLING

Mobile: +46(0)73 5871242

Box 7001 / Kungsgatan 6,
SE-111 43 Stockholm, Sweden

www.redmind.se<http://www.redmind.se/>

**Comment by mimfgg** [comment]
Thanks! 

When it works, you can just merge the pull request.
I don't remember how we set that up but you can probably change the maven goal "install" to "package verify" thus it will skip the local repository install and you should save some disk space ...

**Comment by mimfgg** [comment]
awesome, 2.8.2 is live :)

**Comment by petost** [comment]
Nice!
Turned out there was nothing wrong with Jenkins.
We launched a new redmind website last Friday, the redirect from redmind.se/jenkins disappeared in the process.
Jenkins works fine with the IP, and the redirect should also work now.




[Redmind signatur]

PETTER ÖSTERLING

Mobile: +46(0)73 5871242

Box 7001 / Kungsgatan 6,
SE-111 43 Stockholm, Sweden

www.redmind.se<http://www.redmind.se/>

**Pull request merged**
