### PR TITLE
Add possibility to configure a appium grid

### PR DESCRIPTION
**Pull request by nilols**

### CODE REVIEW

**Comment by SnytaxError** [comment]
@mimfgg @petterfoo @Gurey

**Comment by mimfgg** [comment]
I think there are too many files attached to that commit, no need for the
runner nor the configuration. And you really just needed to extract the
driver creation to a protected method in the GridConfiguration and extend
it in the AppiumGridConfiguration, no need to copy paste the whole class.
Rmtest-appium depends on rmtest-selenium so all that should be visible.

**Comment by nilols** [comment]
The problem was that the Configuration created a GridConfiguration by default, not our new AppiumGridConfiguration, so the only way I could get it to work in our environment is by changing small things in some dependent classes, thereof the copy of them

**Comment by mimfgg** [comment]
You need to use the yaml syntax... The method you are looking at is just the legacy support for the json syntax. Your AppiumGridConfiguration class will be picked up by reflection and Jackson.

Copy pasting the configuration and the runner is really unnecessary...

**Comment by mimfgg** [comment]
I was thinking about something like that:

https://github.com/RedmindAB/RMTest/pull/7

your yaml configuration file would be:

```
drivers:
  - type: appium-grid
    hubIp: the host name or the ip of the selenium grid server
```

**Comment by mimfgg** [comment]
Hi,

Have you guys tried my solution? 

Cheers

**Comment by nilols** [comment]
We did a dirty hack to get pass this issue, but we will try use https://github.com/RedmindAB/RMTest/pull/7 instead

**Pull request closed without merging**
